[project]
name = "gookybot"
version = "0.1.0"
description = "An all-purpose Discord bot."
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "aiohttp>=3.13.1",
    "alembic>=1.17.1",
    "asyncpg>=0.30.0",
    "beautifulsoup4>=4.14.2",
    "colorlog>=6.10.1",
    "discord-py[voice]>=2.6.4",
    "psycopg2-binary>=2.9.11",
    "python-dotenv>=1.2.1",
    "sqlalchemy>=2.0.44",
]

[project.scripts]
bot = "gookybot.main:run"

[tool.setuptools.packages.find]
where = ["src"]
