"""added enabled column

Revision ID: 20d7ab2a382b
Revises: 35eba19ae4a6
Create Date: 2025-11-09 21:43:24.094593

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '20d7ab2a382b'
down_revision: Union[str, Sequence[str], None] = '35eba19ae4a6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('guilds', sa.Column('antispam_enabled', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('guilds', sa.Column('mod_log_channel_id', sa.BigInteger(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('guilds', 'mod_log_channel_id')
    op.drop_column('guilds', 'antispam_enabled')
    # ### end Alembic commands ###
