"""initial database model creations

Revision ID: ff1c3d38e1c8
Revises: 
Create Date: 2025-11-09 19:25:37.032577

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ff1c3d38e1c8'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('autovcs',
    sa.Column('voice_channel_id', sa.BigInteger(), nullable=False),
    sa.Column('user_discord_id', sa.BigInteger(), nullable=False),
    sa.Column('guild_discord_id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('voice_channel_id'),
    sa.UniqueConstraint('user_discord_id', 'guild_discord_id', name='_autovc_user_guild_uc')
    )
    op.create_table('guilds',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('discord_id', sa.BigInteger(), nullable=False),
    sa.Column('prefix', sa.String(length=10), nullable=False),
    sa.Column('engagement_channels', sa.ARRAY(sa.BigInteger()), server_default='{}', nullable=False),
    sa.Column('welcome_enabled', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('welcome_channel_id', sa.BigInteger(), nullable=True),
    sa.Column('leveling_enabled', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('leveling_channel_id', sa.BigInteger(), nullable=True),
    sa.Column('leveling_notify_on_levelup', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('auto_vc_channel_id', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('discord_id')
    )
    op.create_table('leveling_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_discord_id', sa.BigInteger(), nullable=False),
    sa.Column('guild_discord_id', sa.BigInteger(), nullable=False),
    sa.Column('xp', sa.Integer(), nullable=False),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_discord_id', 'guild_discord_id', name='_leveling_profiles_user_guild_uc')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('leveling_profiles')
    op.drop_table('guilds')
    op.drop_table('autovcs')
    # ### end Alembic commands ###
